{
   "total_flags":234,
   "imining_locations":[
      {
         "id":"54",
         "name":"\u00d6sterreich",
         "area":null,
         "flag":"inc\/flags\/AT.gif"
      },
      {
         "id":"14",
         "name":"Afghanistan \u2022 \u0627\u0641\u063a\u0627\u0646\u0633\u062a\u0627",
         "area":null,
         "flag":"inc\/flags\/AF.gif"
      },
      {
         "id":"24",
         "name":"AI",
         "area":null,
         "flag":"inc\/flags\/AI.gif"
      },
      {
         "id":"29",
         "name":"Albania \u2022 Shqip\u00ebria",
         "area":null,
         "flag":"inc\/flags\/AL.gif"
      },
      {
         "id":"45",
         "name":"Algeria \u2022 \u0627\u064e\u0644\u0652\u062c\u064e\u0632\u064e\u0627\u0626",
         "area":null,
         "flag":"inc\/flags\/DZ.gif"
      },
      {
         "id":"39",
         "name":"AN",
         "area":null,
         "flag":"inc\/flags\/AN.gif"
      },
      {
         "id":"151",
         "name":"Andorra",
         "area":null,
         "flag":"inc\/flags\/MD.gif"
      },
      {
         "id":"44",
         "name":"Angola",
         "area":null,
         "flag":"inc\/flags\/AO.gif"
      },
      {
         "id":"19",
         "name":"Antigua & Barbuda",
         "area":null,
         "flag":"inc\/flags\/AG.gif"
      },
      {
         "id":"49",
         "name":"Argentina",
         "area":null,
         "flag":"inc\/flags\/AR.gif"
      },
      {
         "id":"34",
         "name":"Armenia",
         "area":null,
         "flag":"inc\/flags\/AM.gif"
      },
      {
         "id":"5",
         "name":"Australia",
         "area":null,
         "flag":"inc\/flags\/CX.gif"
      },
      {
         "id":"59",
         "name":"Australia",
         "area":null,
         "flag":"inc\/flags\/AU.gif"
      },
      {
         "id":"64",
         "name":"AW",
         "area":null,
         "flag":"inc\/flags\/AW.gif"
      },
      {
         "id":"69",
         "name":"Azerbaidjan",
         "area":null,
         "flag":"inc\/flags\/AZ.gif"
      },
      {
         "id":"104",
         "name":"Bahrain",
         "area":null,
         "flag":"inc\/flags\/BH.gif"
      },
      {
         "id":"84",
         "name":"Bangladesh",
         "area":null,
         "flag":"inc\/flags\/BD.gif"
      },
      {
         "id":"79",
         "name":"Barbados",
         "area":null,
         "flag":"inc\/flags\/BB.gif"
      },
      {
         "id":"89",
         "name":"Belgi\u00eb\/Belgique",
         "area":null,
         "flag":"inc\/flags\/BE.gif"
      },
      {
         "id":"159",
         "name":"Belize",
         "area":null,
         "flag":"inc\/flags\/BZ.gif"
      },
      {
         "id":"114",
         "name":"Benin",
         "area":null,
         "flag":"inc\/flags\/BJ.gif"
      },
      {
         "id":"144",
         "name":"Bhutan",
         "area":null,
         "flag":"inc\/flags\/BT.gif"
      },
      {
         "id":"154",
         "name":"Bielorussia",
         "area":null,
         "flag":"inc\/flags\/BY.gif"
      },
      {
         "id":"129",
         "name":"Bolivia \u00b7 Wuliwya \u00b7 Vol\u00edvia",
         "area":null,
         "flag":"inc\/flags\/BO.gif"
      },
      {
         "id":"74",
         "name":"Bosna i Hercegovina",
         "area":null,
         "flag":"inc\/flags\/BA.gif"
      },
      {
         "id":"149",
         "name":"Botswana",
         "area":null,
         "flag":"inc\/flags\/BW.gif"
      },
      {
         "id":"134",
         "name":"Brazil",
         "area":null,
         "flag":"inc\/flags\/BR.gif"
      },
      {
         "id":"124",
         "name":"Brunei",
         "area":null,
         "flag":"inc\/flags\/BN.gif"
      },
      {
         "id":"99",
         "name":"Bulgaria",
         "area":"Europa",
         "flag":"inc\/flags\/BG.gif"
      },
      {
         "id":"94",
         "name":"Burkina Faso",
         "area":null,
         "flag":"inc\/flags\/BF.gif"
      },
      {
         "id":"194",
         "name":"C\u00f4te d\u2019Ivoire",
         "area":null,
         "flag":"inc\/flags\/CI.gif"
      },
      {
         "id":"234",
         "name":"Cabo Verde",
         "area":null,
         "flag":"inc\/flags\/CV.gif"
      },
      {
         "id":"209",
         "name":"Cameroun",
         "area":null,
         "flag":"inc\/flags\/CM.gif"
      },
      {
         "id":"164",
         "name":"Canada",
         "area":null,
         "flag":"inc\/flags\/CA.gif"
      },
      {
         "id":"204",
         "name":"Chile",
         "area":null,
         "flag":"inc\/flags\/CL.gif"
      },
      {
         "id":"71",
         "name":"Chosun",
         "area":null,
         "flag":"inc\/flags\/KP.gif"
      },
      {
         "id":"224",
         "name":"Costa Rica",
         "area":null,
         "flag":"inc\/flags\/CR.gif"
      },
      {
         "id":"7",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MZ.gif"
      },
      {
         "id":"8",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ST.gif"
      },
      {
         "id":"66",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/KN.gif"
      },
      {
         "id":"68",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/TO.gif"
      },
      {
         "id":"70",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ER.gif"
      },
      {
         "id":"72",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/OM.gif"
      },
      {
         "id":"73",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/TP.gif"
      },
      {
         "id":"80",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ET.gif"
      },
      {
         "id":"81",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/KW.gif"
      },
      {
         "id":"82",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PE.gif"
      },
      {
         "id":"86",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/KY.gif"
      },
      {
         "id":"87",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PF.gif"
      },
      {
         "id":"88",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/TV.gif"
      },
      {
         "id":"90",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/FJ.gif"
      },
      {
         "id":"91",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/KZ.gif"
      },
      {
         "id":"93",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/TW.gif"
      },
      {
         "id":"95",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/FK.gif"
      },
      {
         "id":"96",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LA.gif"
      },
      {
         "id":"98",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/TZ.gif"
      },
      {
         "id":"100",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/FM.gif"
      },
      {
         "id":"102",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PK.gif"
      },
      {
         "id":"103",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/Thumbs.db"
      },
      {
         "id":"105",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/FO.gif"
      },
      {
         "id":"106",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LC.gif"
      },
      {
         "id":"110",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/FR.gif"
      },
      {
         "id":"112",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PM.gif"
      },
      {
         "id":"113",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UG.gif"
      },
      {
         "id":"115",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GA.gif"
      },
      {
         "id":"116",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LR.gif"
      },
      {
         "id":"117",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PN.gif"
      },
      {
         "id":"118",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UK-Alderney.gif"
      },
      {
         "id":"119",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/BM.gif"
      },
      {
         "id":"120",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GB.gif"
      },
      {
         "id":"121",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LS.gif"
      },
      {
         "id":"122",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PR.gif"
      },
      {
         "id":"123",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UK-Guernsey.gif"
      },
      {
         "id":"125",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GD.gif"
      },
      {
         "id":"126",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LT.gif"
      },
      {
         "id":"128",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UK-IOM.gif"
      },
      {
         "id":"131",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LU.gif"
      },
      {
         "id":"133",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UK-Jersey.gif"
      },
      {
         "id":"135",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GF.gif"
      },
      {
         "id":"136",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LV.gif"
      },
      {
         "id":"137",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PW.gif"
      },
      {
         "id":"138",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UK-NI.gif"
      },
      {
         "id":"139",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/BS.gif"
      },
      {
         "id":"141",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/LY.gif"
      },
      {
         "id":"142",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/PY.gif"
      },
      {
         "id":"145",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GI.gif"
      },
      {
         "id":"150",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GL.gif"
      },
      {
         "id":"152",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/RE.gif"
      },
      {
         "id":"155",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GM.gif"
      },
      {
         "id":"156",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MG.gif"
      },
      {
         "id":"160",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GN.gif"
      },
      {
         "id":"161",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MH.gif"
      },
      {
         "id":"165",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GP.gif"
      },
      {
         "id":"166",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MK.gif"
      },
      {
         "id":"167",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/RW.gif"
      },
      {
         "id":"169",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/CC.gif"
      },
      {
         "id":"170",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GQ.gif"
      },
      {
         "id":"171",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ML.gif"
      },
      {
         "id":"173",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/UZ.gif"
      },
      {
         "id":"174",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/CD.gif"
      },
      {
         "id":"176",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MM.gif"
      },
      {
         "id":"177",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SB.gif"
      },
      {
         "id":"178",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/VC.gif"
      },
      {
         "id":"180",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GT.gif"
      },
      {
         "id":"183",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/VE.gif"
      },
      {
         "id":"185",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GW.gif"
      },
      {
         "id":"186",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MO.gif"
      },
      {
         "id":"187",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SD.gif"
      },
      {
         "id":"188",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/VG.gif"
      },
      {
         "id":"190",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/GY.gif"
      },
      {
         "id":"191",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MP.gif"
      },
      {
         "id":"196",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MQ.gif"
      },
      {
         "id":"197",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SG.gif"
      },
      {
         "id":"198",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/VU.gif"
      },
      {
         "id":"199",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/CK.gif"
      },
      {
         "id":"200",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/HN.gif"
      },
      {
         "id":"201",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MR.gif"
      },
      {
         "id":"202",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SH.gif"
      },
      {
         "id":"203",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/WF.gif"
      },
      {
         "id":"206",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MS.gif"
      },
      {
         "id":"207",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SI.gif"
      },
      {
         "id":"208",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/WS.gif"
      },
      {
         "id":"210",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/HT.gif"
      },
      {
         "id":"213",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/YE.gif"
      },
      {
         "id":"215",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/HU.gif"
      },
      {
         "id":"216",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MU.gif"
      },
      {
         "id":"217",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SL.gif"
      },
      {
         "id":"218",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/YU.gif"
      },
      {
         "id":"219",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/CO.gif"
      },
      {
         "id":"220",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ID.gif"
      },
      {
         "id":"221",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MV.gif"
      },
      {
         "id":"222",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SM.gif"
      },
      {
         "id":"226",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MW.gif"
      },
      {
         "id":"228",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ZM.gif"
      },
      {
         "id":"229",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/CU.gif"
      },
      {
         "id":"232",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SO.gif"
      },
      {
         "id":"233",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ZR.gif"
      },
      {
         "id":"236",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/MY.gif"
      },
      {
         "id":"237",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/SR.gif"
      },
      {
         "id":"238",
         "name":"country name",
         "area":null,
         "flag":"inc\/flags\/ZW.gif"
      },
      {
         "id":"10",
         "name":"Cyprus",
         "area":null,
         "flag":"inc\/flags\/CY.gif"
      },
      {
         "id":"15",
         "name":"Czech Republic",
         "area":null,
         "flag":"inc\/flags\/CZ.gif"
      },
      {
         "id":"30",
         "name":"Danmark",
         "area":"Europa",
         "flag":"inc\/flags\/DK.gif"
      },
      {
         "id":"20",
         "name":"Deutschland",
         "area":"Europa",
         "flag":"inc\/flags\/DE.gif"
      },
      {
         "id":"25",
         "name":"Djibouti",
         "area":null,
         "flag":"inc\/flags\/DJ.gif"
      },
      {
         "id":"35",
         "name":"DM",
         "area":null,
         "flag":"inc\/flags\/DM.gif"
      },
      {
         "id":"50",
         "name":"Ecuador",
         "area":null,
         "flag":"inc\/flags\/EC.gif"
      },
      {
         "id":"60",
         "name":"Egypt - \u0645\u064e\u0635\u0652\u0631",
         "area":null,
         "flag":"inc\/flags\/EG.gif"
      },
      {
         "id":"65",
         "name":"EH",
         "area":null,
         "flag":"inc\/flags\/EH.gif"
      },
      {
         "id":"225",
         "name":"Eire",
         "area":null,
         "flag":"inc\/flags\/IE.gif"
      },
      {
         "id":"143",
         "name":"England?",
         "area":"Europa",
         "flag":"inc\/flags\/UK-Sark.gif"
      },
      {
         "id":"76",
         "name":"\ub300\ud55c\ubbfc\uad6d",
         "area":null,
         "flag":"inc\/flags\/KR.gif"
      },
      {
         "id":"75",
         "name":"Espa\u00f1a",
         "area":"1",
         "flag":"inc\/flags\/ES.gif"
      },
      {
         "id":"55",
         "name":"Estonia",
         "area":"Europa",
         "flag":"inc\/flags\/EE.gif"
      },
      {
         "id":"17",
         "name":"France",
         "area":"Europa",
         "flag":"inc\/flags\/NC.gif"
      },
      {
         "id":"130",
         "name":"Georgia",
         "area":null,
         "flag":"inc\/flags\/GE.gif"
      },
      {
         "id":"140",
         "name":"Ghana",
         "area":null,
         "flag":"inc\/flags\/GH.gif"
      },
      {
         "id":"205",
         "name":"Hrvatska",
         "area":null,
         "flag":"inc\/flags\/HR.gif"
      },
      {
         "id":"175",
         "name":"\u0395\u03bb\u03bb\u03ac\u03b4\u03b1",
         "area":null,
         "flag":"inc\/flags\/GR.gif"
      },
      {
         "id":"235",
         "name":"India",
         "area":null,
         "flag":"inc\/flags\/IN.gif"
      },
      {
         "id":"11",
         "name":"Iran - \u0627\u06cc\u0631\u0627\u0646",
         "area":null,
         "flag":"inc\/flags\/IR.gif"
      },
      {
         "id":"6",
         "name":"Iraq - \u0627\u0644\u0639\u0631\u0627\u0642",
         "area":null,
         "flag":"inc\/flags\/IQ.gif"
      },
      {
         "id":"16",
         "name":"Island",
         "area":"Europa",
         "flag":"inc\/flags\/IS.gif"
      },
      {
         "id":"230",
         "name":"Israel",
         "area":null,
         "flag":"inc\/flags\/IL.gif"
      },
      {
         "id":"21",
         "name":"Italia",
         "area":"Europa",
         "flag":"inc\/flags\/IT.gif"
      },
      {
         "id":"26",
         "name":"Jamaica",
         "area":null,
         "flag":"inc\/flags\/JM.gif"
      },
      {
         "id":"31",
         "name":"Jordan - \u0627\u0644\u0623\u0631\u062f\u0646\u200e",
         "area":null,
         "flag":"inc\/flags\/JO.gif"
      },
      {
         "id":"179",
         "name":"K\u00f6d\u00f6r\u00f6s\u00ease t\u00ee B\u00eaafr\u00eeka",
         "area":null,
         "flag":"inc\/flags\/CF.gif"
      },
      {
         "id":"51",
         "name":"K\u00e2mp\u016dch\u00e9a",
         "area":null,
         "flag":"inc\/flags\/KH.gif"
      },
      {
         "id":"41",
         "name":"Kenya",
         "area":null,
         "flag":"inc\/flags\/KE.gif"
      },
      {
         "id":"46",
         "name":"Kirgizstan",
         "area":null,
         "flag":"inc\/flags\/KG.gif"
      },
      {
         "id":"56",
         "name":"Kiribati",
         "area":null,
         "flag":"inc\/flags\/KI.gif"
      },
      {
         "id":"61",
         "name":"KM",
         "area":null,
         "flag":"inc\/flags\/KM.gif"
      },
      {
         "id":"101",
         "name":"Lebanon",
         "area":null,
         "flag":"inc\/flags\/LB.gif"
      },
      {
         "id":"42",
         "name":"Luxembourg",
         "area":null,
         "flag":"inc\/flags\/NL.gif"
      },
      {
         "id":"211",
         "name":"Malta",
         "area":null,
         "flag":"inc\/flags\/MT.gif"
      },
      {
         "id":"231",
         "name":"Mexico",
         "area":null,
         "flag":"inc\/flags\/MX.gif"
      },
      {
         "id":"181",
         "name":"Mongolia",
         "area":null,
         "flag":"inc\/flags\/MN.gif"
      },
      {
         "id":"146",
         "name":"Morocco",
         "area":null,
         "flag":"inc\/flags\/MA.gif"
      },
      {
         "id":"12",
         "name":"Namibia",
         "area":null,
         "flag":"inc\/flags\/NA.gif"
      },
      {
         "id":"57",
         "name":"Nauru - Naoero",
         "area":null,
         "flag":"inc\/flags\/NR.gif"
      },
      {
         "id":"22",
         "name":"NE",
         "area":null,
         "flag":"inc\/flags\/NE.gif"
      },
      {
         "id":"52",
         "name":"Nepal",
         "area":null,
         "flag":"inc\/flags\/NP.gif"
      },
      {
         "id":"67",
         "name":"New Zealand",
         "area":null,
         "flag":"inc\/flags\/NZ.gif"
      },
      {
         "id":"27",
         "name":"NF",
         "area":null,
         "flag":"inc\/flags\/NF.gif"
      },
      {
         "id":"37",
         "name":"Nicaragua",
         "area":null,
         "flag":"inc\/flags\/NI.gif"
      },
      {
         "id":"32",
         "name":"Nigeria",
         "area":null,
         "flag":"inc\/flags\/NG.gif"
      },
      {
         "id":"36",
         "name":"Nihon",
         "area":null,
         "flag":"inc\/flags\/JP.gif"
      },
      {
         "id":"47",
         "name":"Norge",
         "area":null,
         "flag":"inc\/flags\/NO.gif"
      },
      {
         "id":"111",
         "name":"not Bhutan",
         "area":null,
         "flag":"inc\/flags\/LK.gif"
      },
      {
         "id":"62",
         "name":"NU",
         "area":null,
         "flag":"inc\/flags\/NU.gif"
      },
      {
         "id":"157",
         "name":"\u062a\u0650\u0634\u064e\u0627\u062f",
         "area":null,
         "flag":"inc\/flags\/RO.gif"
      },
      {
         "id":"127",
         "name":"Palestina",
         "area":null,
         "flag":"inc\/flags\/PS.gif"
      },
      {
         "id":"77",
         "name":"Panama",
         "area":null,
         "flag":"inc\/flags\/PA.gif"
      },
      {
         "id":"92",
         "name":"Papua\/New Guinea",
         "area":null,
         "flag":"inc\/flags\/PG.gif"
      },
      {
         "id":"97",
         "name":"Phillipines",
         "area":null,
         "flag":"inc\/flags\/PH.gif"
      },
      {
         "id":"107",
         "name":"Poland",
         "area":"Europa",
         "flag":"inc\/flags\/PL.gif"
      },
      {
         "id":"132",
         "name":"Portugal",
         "area":"Europa",
         "flag":"inc\/flags\/PT.gif"
      },
      {
         "id":"214",
         "name":"PR China",
         "area":null,
         "flag":"inc\/flags\/CN.gif"
      },
      {
         "id":"147",
         "name":"Qatar",
         "area":null,
         "flag":"inc\/flags\/QA.gif"
      },
      {
         "id":"184",
         "name":"R\u00e9publique du Congo",
         "area":null,
         "flag":"inc\/flags\/CG.gif"
      },
      {
         "id":"40",
         "name":"Rep. Dominicaine",
         "area":null,
         "flag":"inc\/flags\/DO.gif"
      },
      {
         "id":"162",
         "name":"Russia",
         "area":"Europa",
         "flag":"inc\/flags\/RU.gif"
      },
      {
         "id":"172",
         "name":"Saudi Arabia",
         "area":null,
         "flag":"inc\/flags\/SA.gif"
      },
      {
         "id":"189",
         "name":"Schweiz",
         "area":null,
         "flag":"inc\/flags\/CH.gif"
      },
      {
         "id":"148",
         "name":"Scotland",
         "area":"Europa",
         "flag":"inc\/flags\/UK-Scotland.gif"
      },
      {
         "id":"182",
         "name":"Scotland (again)",
         "area":null,
         "flag":"inc\/flags\/SC.gif"
      },
      {
         "id":"227",
         "name":"Senegal",
         "area":null,
         "flag":"inc\/flags\/SN.gif"
      },
      {
         "id":"212",
         "name":"Slovakia",
         "area":null,
         "flag":"inc\/flags\/SK.gif"
      },
      {
         "id":"13",
         "name":"Slovenija",
         "area":null,
         "flag":"inc\/flags\/SV.gif"
      },
      {
         "id":"223",
         "name":"South Africa",
         "area":null,
         "flag":"inc\/flags\/ZA.gif"
      },
      {
         "id":"85",
         "name":"Suomi",
         "area":"Europa",
         "flag":"inc\/flags\/FI.gif"
      },
      {
         "id":"192",
         "name":"Svierge",
         "area":null,
         "flag":"inc\/flags\/SE.gif"
      },
      {
         "id":"23",
         "name":"Swaziland",
         "area":null,
         "flag":"inc\/flags\/SZ.gif"
      },
      {
         "id":"18",
         "name":"Syria - \u0633\u0648\u0631\u064a\u0629\u200e",
         "area":null,
         "flag":"inc\/flags\/SY.gif"
      },
      {
         "id":"78",
         "name":"T\u00fcrkiye",
         "area":null,
         "flag":"inc\/flags\/TR.gif"
      },
      {
         "id":"195",
         "name":"Taiwan",
         "area":null,
         "flag":"inc\/flags\/HK.gif"
      },
      {
         "id":"28",
         "name":"TC",
         "area":null,
         "flag":"inc\/flags\/TC.gif"
      },
      {
         "id":"33",
         "name":"TD",
         "area":null,
         "flag":"inc\/flags\/TD.gif"
      },
      {
         "id":"43",
         "name":"Thailand - \u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e44",
         "area":null,
         "flag":"inc\/flags\/TH.gif"
      },
      {
         "id":"48",
         "name":"TJ",
         "area":null,
         "flag":"inc\/flags\/TJ.gif"
      },
      {
         "id":"53",
         "name":"TK",
         "area":null,
         "flag":"inc\/flags\/TK.gif"
      },
      {
         "id":"38",
         "name":"Togo",
         "area":null,
         "flag":"inc\/flags\/TG.gif"
      },
      {
         "id":"83",
         "name":"Trinidad & Tobago",
         "area":null,
         "flag":"inc\/flags\/TT.gif"
      },
      {
         "id":"63",
         "name":"Turkey",
         "area":null,
         "flag":"inc\/flags\/TN.gif"
      },
      {
         "id":"58",
         "name":"Turkmenistan",
         "area":null,
         "flag":"inc\/flags\/TM.gif"
      },
      {
         "id":"9",
         "name":"UAE - \u0627\u0644\u0627\u0645\u0627\u0631\u0627\u062a",
         "area":null,
         "flag":"inc\/flags\/AE.gif"
      },
      {
         "id":"109",
         "name":"uBurundi",
         "area":null,
         "flag":"inc\/flags\/BI.gif"
      },
      {
         "id":"108",
         "name":"Ukraina",
         "area":null,
         "flag":"inc\/flags\/UA.gif"
      },
      {
         "id":"158",
         "name":"United Kingdom",
         "area":"Europa",
         "flag":"inc\/flags\/UK.gif"
      },
      {
         "id":"168",
         "name":"Uruguay",
         "area":null,
         "flag":"inc\/flags\/UY.gif"
      },
      {
         "id":"163",
         "name":"USA",
         "area":null,
         "flag":"inc\/flags\/US.gif"
      },
      {
         "id":"193",
         "name":"Vietnam",
         "area":null,
         "flag":"inc\/flags\/VN.gif"
      },
      {
         "id":"153",
         "name":"Wales",
         "area":"Europa",
         "flag":"inc\/flags\/UK-Wales.gif"
      }
   ]
}